### PR TITLE
removed global 'copy' array prototype extension

### PR DESCRIPTION
**Pull request by dpolica**
Hi Richard,
I have forked the library in order to avoid overwriting the copy prototype of the array, in order to be compatible with JS code that uses the for..in pattern to iterate arrays.

Let me know if you have concerns with that
Kind Regards
Davide

### CODE REVIEW

**Comment by ricmoo** [comment]
Oh! Good idea, I'll download it tomorrow and test it out, but looks good.

**Comment by ricmoo** [comment]
Sorry, I've been quite busy lately with some Ethereum stuff I'm getting put together. I will get back to this soon. :)

**Comment by dpolica** [comment]
No problem

Let me know when you are done



Thanks you very much

Regards

Davide





*From:* Richard Moore [mailto:notifications@github.com]
*Sent:* Wednesday, March 30, 2016 11:18 AM
*To:* ricmoo/aes-js
*Cc:* davide polica
*Subject:* Re: [ricmoo/aes-js] removed global 'copy' array prototype
extension (#7)



Sorry, I've been quite busy lately with some Ethereum stuff I'm getting put
together. I will get back to this soon. :)

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/ricmoo/aes-js/pull/7#issuecomment-203340281>

**Comment by ricmoo** [comment]
Hey @dpolica,

This has been fixed in change https://github.com/ricmoo/aes-js/commit/a32bf1b0a1505f3d1d7137af8e62fa318a5d601c.

I've been adding updates and pull requests for a bit today, and only have one more to get to, then I will publish the new version to npm (as a major version change).

Thanks again,
RicMoo

**Pull request closed without merging**
