### PR TITLE
Fixed TypedArray compatibility with Safari and IE 10

### PR DESCRIPTION
**Pull request by jkrcma**
Hi!

We proudly used your library in our micro project https://github.com/skooda/passIon, but despite our best tries the aes-js didn't work in Safari. So here is the fix

### CODE REVIEW

**Comment by Spy-Seth** [comment]
:+1:

**Comment by shouze** [comment]
@jkrcma can you please point out some documentation and/or issue about that fix?

**Comment by ricmoo** [comment]
Sorry, I totally lost track of this.

What problem are you having in Safari? The test.html in the test directory shows that all the existing test cases pass (I just tested in Safari). Can you provide a test case where it fails?

Thanks!
RicMoo

**Comment by jkrcma** [comment]
Sorry that I didn't provide tests, I'm not much a JavaScript guy. Since it has been a while I had to remember what was the problem. Actually, the `TypedArray.prototype.slice()` isn't supported in all browsers yet, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice

**Comment by ricmoo** [comment]
I've fixed this by copying the object into an array if slice isn't supported. Any object that supports `.length` and has all the necessary properties over the interval [0, length) can be used.

**Pull request closed without merging**
