### PR TITLE
Replace Buffer constructor with static methods

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes: https://github.com/ricmoo/aes-js/issues/68

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@Ruffio I have removed the `Buffer.fill(42)` line.

**Comment by Ruffio** [comment]
@gabrielschulhof ready to be merged?

**Comment by gabrielschulhof** [comment]
@Ruffio yep!

**Comment by gabrielschulhof** [comment]
@Ruffio this should be ready to go. Can you please land it?

**Comment by Ruffio** [comment]
@gabrielschulhof I'm just a user like you. Only @ricmoo can merge PR...

**Comment by gabrielschulhof** [comment]
@ricmoo could you PTAL?

**Comment by ricmoo** [comment]
There are a few changes I need to merge. I will try to get to this soon.

**Comment by ricmoo** [comment]
Thanks! :)

**Pull request merged**
