### PR TITLE
Added bower.json file, registered

### PR DESCRIPTION
**Pull request by lmartorella**
Hello,
I've tried to register the library on bower, to use it in the browser, and everything seems OK.
In this commit I only added the bower file, very simple (it doesn't even clean the output from the tests, etc...).
If this PR is accepted, we can change the bower public registry to point to your original repo instead this forked one.

Thank you,
 Luciano

### CODE REVIEW

**Comment by ricmoo** [comment]
Cool, I've never used bower, but if it looks ok to me. I will likely update the "homepage" parameter in the future to reflect the main repository, if there are no objections. :)

**Comment by lmartorella** [comment]
Cool, thanks!
I've just update the bower registry in order to point to the main repository (I'll remove my fork soon), so definitively yes, the homepage parameter should be fixed as well!
Cheers,
 Luciano

**Comment by lmartorella** [comment]
Hi, could you please create a git tag following the standard semver conventions? When I moved the bower registry from my fork back to the main repository, we are unable to address the proper "0.2.1" version (the workaround is to not set any tag name, but this is not recommended...).
Thanks,
 Luciano

**Comment by ricmoo** [comment]
Heya!

I've updated the bower file, bumped the version to 0.2.2, created the tag and republished to npm. Is there anything additionally I need to do for bower to pick up the version of 0.2.2?

**Comment by lmartorella** [comment]
Great, no other actions are required. Bower will fetch packages that are referred by version/tag name using git tags.
Thank you!
 Luciano

**Pull request merged**
