### PR TITLE
Fix typo in AES Error Message

### PR DESCRIPTION
**Pull request by yne**
While writing the documentation about the deezer HTML5 player, I found a cute typo that led me to this PR.

### CODE REVIEW

**Comment by yne** [comment]
@ricmoo I know this is not a relly important PR so I can close it if you want

**Comment by Ruffio** [comment]
https://github.com/ricmoo/aes-js/pull/95 covers more typos and should be merged :-)

**Comment by yne** [comment]
Good to know, I'll close this MR then.

**Comment by ricmoo** [comment]
Oh! I’ll get to this. You can leave it open. I’ve been busy with v5 of ethers, which will hopefully be out soon (tm). :)

**Comment by yne** [comment]
The #95 is way more complet that this one, so it's fine :)

I fixed the typo just to see how often the Dezzer dev team upgrade they node dependencies.

**Pull request closed without merging**
